=== saliou33/xml-app/xml/resto.dtd
<!ELEMENT fiche (coordonnées, nom, adresse, nomRestaurant, description?, carte, menus?)>
<!ELEMENT coordonnées (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT nomRestaurant (#PCDATA)>
<!ELEMENT description (#PCDATA|liste|paragraphe|important|img)*>
<!ELEMENT liste (element+)>
<!ELEMENT element (#PCDATA)>
<!ELEMENT paragraphe (#PCDATA)>
<!ELEMENT important (#PCDATA)>
<!ELEMENT img EMPTY>
<!ATTLIST img url CDATA #REQUIRED position (droite|gauche|centre) #IMPLIED>
<!ELEMENT carte (plat+)>
<!ELEMENT plat (prix, descriptionPlat?)>
<!ATTLIST plat type (entrée|dessert|plat|fromage) #IMPLIED>
<!ELEMENT descriptionPlat (paragraphe, important*)>
<!ELEMENT menus (menu+)>
<!ATTLIST menus ordre (prix|choix) #IMPLIED>
<!ELEMENT menu (titre, prix, plats)>
<!ELEMENT plats (plat+)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ATTLIST prix devise CDATA #REQUIRED>

=== saliou33/xml-app/xml/data/resto/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fiche SYSTEM "../../resto.dtd">
<fiche>
    <coordonnées>
        Lat:14.6937, Long:-17.44406
    </coordonnées>
    <nom>Serigne Saliou LO</nom>
    <adresse> Liberte 6 extension </adresse>
    <nomRestaurant>Peace Resto</nomRestaurant>
    <description>
        <important>Peace Resto</important>
        <img url="peaceresto.sn" position="centre"/>
        Un restaurant aux plats delicieux et variees...
    </description>
    <carte>
        <plat type="plat">
            <prix devise="XOF">1500</prix>
            <descriptionPlat>
                <paragraphe>
                    Thiebou Diagua bou saff sapp té nekh
                </paragraphe>
                <important>Sauce Simple</important>
                <important>Sauce Piment</important>
            </descriptionPlat>
        </plat>
        <plat type="plat">
            <prix devise="XOF">1300</prix>
            <descriptionPlat>
                <paragraphe>
                    Thiebou Dieune Penda Mbaye
                </paragraphe>
                <important>Avec Sauce</important>
                <important>Sans Sauce</important>
            </descriptionPlat>
        </plat>
        <plat type="dessert">
            <prix devise="XOF">250</prix>
            <descriptionPlat>
                <paragraphe>
                    Jus Bissap
                </paragraphe>
            </descriptionPlat>
        </plat>
    </carte>

    <menus ordre="prix">
        <menu>
            <titre>Repas Senegalaise</titre>
            <prix devise="XOF">1800</prix>
            <plats>
                <plat type="plat">
                    <prix devise="XOF">1300</prix>
                    <descriptionPlat>
                        <paragraphe>
                            Thiebou Dieune Penda Mbaye
                        </paragraphe>
                        <important>Avec Sauce</important>
                        <important>Sans Sauce</important>
                    </descriptionPlat>
                </plat>
                <plat type="dessert">
                    <prix devise="XOF">250</prix>
                    <descriptionPlat>
                        <paragraphe>
                            Jus Bissap
                        </paragraphe>
                    </descriptionPlat>
                </plat>
            </plats>
        </menu>
    </menus>
</fiche>
